#quantity per cli-application
sensors:
  quantity: 1
  unit: 3834792229
  #Interval in ms
  publishinterval: 5000
  publishquantity: 20
  msp: UFSC

sellers:
  quantity: 200
  #Interval in ms
  publishinterval: 5000
  publishquantity: 10
  msp: UFSC


buyers:
  quantity: 10
  #Interval in ms
  publishinterval: 5000
  publishquantity: 20
  msp: IDEMIXORG

#Interval in ms
auctioninterval: 30000

utilityurl: http://localhost
paymentcompanyurl: http://localhost:81


