sensors:
  quantity: 1
  unit: 3834792229
  #Interval in ms
  publishinterval: 1000
  publishquantity: 200
  msp: UFSC

sellers:
  quantity: 1
  #Interval in ms
  publishinterval: 2000
  publishquantity: 1
  msp: UFSC


buyers:
  quantity: 1
  #Interval in ms
  publishinterval: 2000
  publishquantity: 1
  msp: IDEMIXORG

utilityurl: http://localhost
paymentcompanyurl: http://localhost:81
#Interval in ms
auctioninterval: 10000