sensors:
  quantity: 5
  unit: 3834792229
  #Interval in ms
  publishinterval: 5000
  publishquantity: 10
  msp: UFSC

sellers:
  quantity: 5
  #Interval in ms
  publishinterval: 5000
  publishquantity: 10
  msp: UFSC


buyers:
  quantity: 5
  #Interval in ms
  publishinterval: 5000
  publishquantity: 10
  msp: IDEMIXORG

utilityurl: http://localhost
paymentcompanyurl: http://localhost:81
#Interval in ms
auctioninterval: 30000