sensors:
  quantity: 10
  unit: 3834792229
  #Interval in ms
  publishinterval: 5000
  publishquantity: 20
  msp: UFSC

sellers:
  quantity: 10
  #Interval in ms
  publishinterval: 5000
  publishquantity: 20
  msp: UFSC


buyers:
  quantity: 10
  #Interval in ms
  publishinterval: 5000
  publishquantity: 20
  msp: IDEMIXORG

utilityurl: http://localhost
paymentcompanyurl: http://localhost:81
#Interval in ms
auctioninterval: 30000

#terraform